"""
SUPABASE VECTOR STORE (Postgres + pgvector)
Drop-in replacement for HybridChromaStore using Supabase.
"""

import os
import logging
from typing import List, Dict, Optional, Any
from pathlib import Path
import json
from sentence_transformers import SentenceTransformer
import numpy as np
from supabase import create_client, Client

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class SupabaseHybridStore:
    """
    Hybrid Vector Store using Supabase (PostgreSQL + pgvector).
    Performs Hybrid Search (Keyword + Vector) via server-side SQL function.
    """
    
    def __init__(
        self,
        supabase_url: str = None,
        supabase_key: str = None,
        embedding_model: str = "sentence-transformers/all-MiniLM-L6-v2"
    ):
        """
        Initialize Supabase Store
        """
        self.supabase_url = supabase_url or os.getenv("SUPABASE_URL")
        self.supabase_key = (
            supabase_key
            or os.getenv("SUPABASE_SERVICE_ROLE_KEY")
            or os.getenv("SUPABASE_KEY")
            or os.getenv("SUPABASE_ANON_KEY")
        )
        
        if not self.supabase_url or not self.supabase_key:
            raise ValueError(
                "SUPABASE_URL and one of SUPABASE_SERVICE_ROLE_KEY, SUPABASE_KEY, or SUPABASE_ANON_KEY must be set in environment variables or passed to constructor."
            )
            
        logger.info(f"Initializing Supabase Client: {self.supabase_url}")
        self.client: Client = create_client(self.supabase_url, self.supabase_key)
        
        # Load embedding model locally (same as before)
        logger.info(f"Loading embedding model: {embedding_model}")
        self.embedding_model = SentenceTransformer(embedding_model)
        self.embedding_dim = self.embedding_model.get_sentence_embedding_dimension()
        
    def add_documents(
        self, 
        documents: List[Dict],
        batch_size: int = 50,
        show_progress: bool = True
    ):
        """
        Add documents to Supabase
        
        Args:
            documents: List[Dict] with 'text' and 'metadata'. 'id' is optional (auto-generated by DB if not provided, or we can enforce it).
            batch_size: Upload batch size
        """
        logger.info(f"Preparing to add {len(documents)} documents to Supabase...")
        
        # Generate embeddings in batches
        total_batches = (len(documents) + batch_size - 1) // batch_size
        
        for i in range(0, len(documents), batch_size):
            batch = documents[i:i+batch_size]
            batch_texts = [doc['text'] for doc in batch]
            
            # Generate Embeddings
            embeddings = self.embedding_model.encode(
                batch_texts, 
                show_progress_bar=False
            ).tolist()
            
            # Prepare rows
            rows = []
            for j, doc in enumerate(batch):
                row = {
                    "content": doc['text'],
                    "metadata": doc.get('metadata', {}),
                    "embedding": embeddings[j]
                }
                # If ID is provided and relevant, we could include it, but SERIAL usually handles it
                # if 'id' in doc: row['id'] = doc['id'] 
                rows.append(row)
            
            # Insert into Supabase
            try:
                data, count = self.client.table("documents").insert(rows).execute()
                if show_progress:
                    print(f"Uploaded batch {i//batch_size + 1}/{total_batches}")
            except Exception as e:
                import traceback
                logger.error(f"Error inserting batch: {e}")
                logger.error(traceback.format_exc())
                
        logger.info(f"Successfully added {len(documents)} documents to Supabase.")

    def hybrid_search(
        self,
        query: str,
        n_results: int = 5,
        alpha: float = 0.5  # Not used directly, as SQL function handles weighting
    ) -> List[Dict]:
        """
        Perform Hybrid Search using Supabase RPC function
        """
        # Generate query embedding
        query_embedding = self.embedding_model.encode(query).tolist()
        
        # Call RPC function 'hybrid_search'
        try:
            params = {
                "query_text": query,
                "query_embedding": query_embedding,
                "match_count": n_results,
                "full_text_weight": 1.0, 
                "semantic_weight": 1.0,
                "rrf_k": 50
            }
            
            response = self.client.rpc("hybrid_search", params).execute()
            # Response format: data object (list of dicts)
            results = response.data 
            
            # Format results to match expected interface
            formatted_results = []
            for item in results:
                formatted_results.append({
                    "id": str(item['id']),
                    "text": item['content'],
                    "metadata": item['metadata'],
                    "score": item['score'],
                    "source": "supabase_hybrid"
                })
                
            return formatted_results
            
        except Exception as e:
            logger.error(f"Supabase Search Error: {e}")
            return []

    def get_collection_info(self) -> Dict:
        """Get info mimicking Chroma interface"""
        try:
            count_response = self.client.table("documents").select("id", count="exact").execute()
            count = count_response.count
        except:
            count = 0
            
        return {
            "name": "supabase_documents",
            "count": count,
            "type": "postgres_vector"
        }
